export const environment = {
  production: false,
  envName: 'ausdev',
  baseUrl: 'https://hcc-dev.oktapreview.com',
  OktaBaseUrl: 'https://hcc-dev.oktapreview.com/api/v1/',
  OktaAuthorizationKey: 'SSWS 00UqvJLEg_jAgDyZ7rybXtiGNxd41HT41A1-Kkujtn',
  clientId: '0oapicaodgrbpk03j0h7',
  issuer: 'https://hcc-dev.oktapreview.com/oauth2/ausp36l43hu4ac7FY0h7',
  redirectUri: 'https://pasausdev.hcc.com/',
  apiUrl: 'http://localhost:61526/protected',
  WEBSITE_URL: 'https://pasausdev.hcc.com/api/sitecore/',
  OCTAAPI_END_POINT: 'https://6lbilgditb.execute-api.us-east-1.amazonaws.com/QA/',
  assetsPath: './assets/apps/ngGTPPAS/assets',
  xapikey: 'kxuyl1ruwb94F6C3YeNMP5woJbfoO0hY5DTmIASP',
  $G_Username: 'BB3TokioMarineRACVAuTravelUAT',
  veriskUrl: 'https://gatewayuat.verisk.com',
  sitecoreBaseAddress: 'https://tmhccsitecoredev-125810-single.azurewebsites.net',
  AgentContactId: '1459123',
  SitecoreBaseAddress: 'https://racvdev.tmmatravel.com/GTPItemService/GetItemData?itemId=',
  Sitecore_Content_Response_Models: 'sitecore/Response-Models/',
  Sitecore_Children: '/children/?includeStandardTemplateFields=false&fields=ItemId,ItemName',
};
